[package]
name        = "signatory"
description = "Multi-provider digital signature library with Ed25519 support"
version     = "0.0.0"
license     = "MIT/Apache-2.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
categories  = ["cryptography", "no-std"]
keywords    = ["cryptography", "security", "signatures"]
repository  = "https://github.com/tendermint/signatory"
readme      = "README.md"

[dependencies]
curve25519-dalek = { version = "= 0.14.0", optional = true, default-features = false }
ed25519-dalek = { version = "= 0.6.0", optional = true, default-features = false, features = ["sha2"] }
failure = { version = "0.1", default-features = false }
failure_derive = { version = "0.1", default-features = false }
sha2 = { version = "0.6", optional = true }
yubihsm = { version = "0.1", optional = true }

[features]
dalek = ["curve25519-dalek", "ed25519-dalek", "sha2"]
default = ["dalek"]
yubihsm2 = ["yubihsm"]

[patch.crates-io]
yubihsm = { git = "https://github.com/coreos/yubihsm-rs" }
